name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Actualizar Browserslist (opcional pero recomendado)
      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest

      # Paso 5: Construir el proyecto
      # Desactiva process.env.CI para evitar errores por advertencias
      - name: Build project
        run: |
          CI=false npm run build

      # Paso 6: Desplegar en Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
